defmodule ShotElixirWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :shot_elixir

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_shot_elixir_key",
    signing_salt: "V3S25m0o",
    same_site: "Lax"
  ]

  @websocket_options [
    compress: false,
    subprotocols: ["actioncable-v1-json", "phoenix"],
    connect_info: [:peer_data, :x_headers, :uri, :user_agent],
    timeout: 45_000
  ]

  # WebSocket support for real-time channels
  socket "/socket", ShotElixirWeb.UserSocket,
    websocket: @websocket_options,
    longpoll: false

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :shot_elixir,
    gzip: not code_reloading?,
    only: ShotElixirWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :shot_elixir
  end

  # CORS configuration
  plug CORSPlug,
    origin: [
      "http://localhost:3001",
      "http://localhost:3000",
      "https://shot-client-phoenix.fly.dev",
      "https://shot-client-next.fly.dev"
    ],
    credentials: true,
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    headers: [
      "Accept",
      "Authorization",
      "Content-Type",
      "Origin",
      "X-Requested-With"
    ],
    expose: ["Authorization"],
    max_age: 86400

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug ShotElixirWeb.Router
end
