import Config

# Configure your database
config :shot_elixir, ShotElixir.Repo,
  username: "isaacpriestley",
  password: "",
  hostname: "localhost",
  database: "shot_counter_local",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :shot_elixir, ShotElixirWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4002],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "JoHFLIXcuPCEi7MrfonK2TcL2siEx5c+6e2CNftVazyaMc1sUnifG+jTYiEf999V",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :shot_elixir, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# ImageKit credentials for development
config :shot_elixir, :imagekit,
  private_key: "private_tR/jCUDO7Q6eSDGhC4e/pyyTKIs=",
  public_key: "public_nyNChhUq1KWjp2I+YYI+lhAzPmk=",
  id: "nvqgwnjgv",
  url_endpoint: "https://ik.imagekit.io/nvqgwnjgv",
  environment: :dev
